### ISSUE TITLE
Convert if statements in visitor-demo.c to g_assert()

### ISSUE THREAD

**Issue by lawrancej** [lawrancej/CompilerKit#18]

**Comment by mrpenguin7** [comment]
I will do this once I get my cmake working.

**Comment by lawrancej** [comment]
By the way, Mike, let me know if there's anything I can do to help you get cmake working. What was the error?

**Comment by mrpenguin7** [comment]
Thanks, I just got it working. I had a could not find cache error, which I fixed by running the command "cmake ." in the CompilerKit directory (which generated the cache file). After that the "cmake --build ." command works fine.

Now that this works I will add the g_asserts tomorrow and then take another issue.
